### ISSUE TITLE
The Module numbers doesn't correlate with the Modules in the course

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions#2]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
The lab list needs to be used by MCTs using either the Skillpipe or the Learn content. Currently that is list of Learn modules in the digital Collection that was provided. Maybe we should just remove "Module x":? There are only 11 to match up.

**Comment by TommyKobber** [comment]
@staleycyn I agree, just remove the module numbers. I don't know how many MCTs use Skillpipe or Learn, so I don't know which setup should be prioritized
