### ISSUE TITLE
Remove module entries from list without case studies

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions#3]
# Module: 5, 8, 10, 11
#### Step: 00

Description of issue: Please remove case study entries for Modules 5, 8, 10 and 11 from the list as there are no case studies available to solve for mentioned modules. Thanks

**Comment by staleycyn** [comment]
The HTML page listings says, "No formal case study". And the Learn Collection does not show them - https://docs.microsoft.com/en-us/users/msftofficialcurriculum-4292/collections/zwm5cy2ownzz08
