### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by Mist3** [MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions#4]
# Module: 00
#### Step: 00

Description of issue
In description of case 06-Apparchitecture there is a broken link to image.

AS-IS: https://github.com/MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions/blob/master/media/Apparchitecture.png

SHOULD BE (?): https://github.com/MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions/blob/master/Instructions/CaseStudy/media/Apparchitecture.png?raw=true

**Comment by staleycyn** [comment]
Should be fixed now. Write back if not. Thanks.
