### ISSUE TITLE
Module 9 Option B

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions#5]
# Module: 09
#### Step: 00

Description of issue: Incorrect Solution provided for case study of Module 9 Option 2

The instructor solution provided for Module 9 Option 2 has a major mistake in it. The solution is available in Trainer Guide. Where should I contact to get it fixed. Thanks

**Comment by staleycyn** [comment]
You can open a support ticket on the MCT Support Forum. Reminder that the solution is not intended to be an exhaustive list of all the possible recommendations. Also, the diagram was changed to remove the subnet and vnet icons to make the solution less specific. There is an update to the course today, so expect new materials in the MCT DLC. Network Option 2 will become the only Network case study.
