### ISSUE TITLE
Module 9 Option 1

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-305-DesigningMicrosoftAzureInfrastructureSolutions#6]
# Module: 09 Option 1

Description of issue: Kindly delete this lab as it has been removed from course on 28th January. thanks

**Comment by staleycyn** [comment]
The trainer solution file will be updated and added to the MCT DLC today.

**Comment by azharkhuwaja** [comment]
![Untitled](https://user-images.githubusercontent.com/49203962/154687866-9d381fa5-40d4-4b23-8584-0e304d4ecd25.png)

**Comment by staleycyn** [comment]
Is there a problem with leaving the Markdown file in folder? The option was removed from the HTML student page.

**Comment by azharkhuwaja** [comment]
I can still access the html page but you can close this issue now. Thanks for your help.

**Comment by staleycyn** [comment]
My HTML page does not show the removed Network case study. 
![image](https://user-images.githubusercontent.com/45440075/154729456-02267d80-07ee-4095-9736-495410275805.png)
